# -*- coding: utf-8 -*-
"""train_and_save_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10vMSwT_S4maHnj0kf2iTzgdr0TIqa2Gi
"""

import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import joblib

# Load dataset
df = pd.read_csv("train.csv")

# Prepare data
X = df.drop(columns=['ID', 'Class/ASD'])
y = df['Class/ASD']

# Encode categorical columns
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = LabelEncoder().fit_transform(X[col])

# Train model
model = RandomForestClassifier(random_state=42)
model.fit(X, y)

# Save model to file
joblib.dump(model, "autism_prediction_model.pkl")
print("✅ Model saved as 'autism_prediction_model.pkl'")